service: nft-mrkt-backend

custom:
  NODE_ENV:
    stage: staging
    develop: development

provider:
  name: aws
  runtime: nodejs14.x
  timeout: 180
  lambdaHashingVersion: 20201221
  logs:
    httpApi: true
  environment:
    NODE_ENV: ${self:custom.NODE_ENV.${self:provider.stage}}

  stage: ${opt:stage, 'develop'}
  region: ap-south-1

functions:
  node-microservice:
    handler: src/lambda.handler
    events:
      - http:
          path: /{proxy+}
          method: any
          cors:
            origin: "*"
            headers: "*"
