service: nft-mrkt-backend

provider:
  name: aws
  runtime: nodejs14.x
  timeout: 180
  lambdaHashingVersion: 20201221
  logs:
    httpApi: true
  environment:
    JWT_SECRET_KEY: secretKey
  stage: ${opt:stage, 'develop'}
  region: ap-south-1

functions:
  node-microservice:
    handler: src/lambda.handler
    events:
      - http:
          path: /{proxy+}
          method: any
          cors:
            origin: "*"
            headers: "*"
